# alacritty config file
# see https://alacritty.org/config-alacritty.html

import = ["/home/will/.config/alacritty/one-half-dark-alacritty.toml"]

[font]
size = 14

[font.bold]
family = "monospace"

[font.bold_italic]
family = "monospace"

[font.italic]
family = "monospace"

[font.normal]
family = "monospace"

[window]
dynamic_title = false
#opacity = 0.98

[window.padding]
x = 3
y = 3
